[build]
  publish = "."

[[redirects]]
  from = "/portal"
  to = "/portal.html"
  status = 200

[[redirects]]
  from = "/cong-dich-vu"
  to = "/portal.html"
  status = 200

[[redirects]]
  from = "/thicongpccc"
  to = "/landing-v3.html"
  status = 200

[[redirects]]
  from = "/landing-v3"
  to = "/landing-v3.html"
  status = 200

[[redirects]]
  from = "/v3"
  to = "/landing-v3.html"
  status = 200

[[redirects]]
  from = "/landing-v2"
  to = "/landing-v2.html"
  status = 200

[[redirects]]
  from = "/v2"
  to = "/landing-v2.html"
  status = 200

[[redirects]]
  from = "/tra-cuu"
  to = "/landing-v2.html#tra-cuu-pccc"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM *"
    Access-Control-Allow-Origin = "*"
